//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActaAperturaEconomica
    {
        public int Id { get; set; }
        public int IdPrograma { get; set; }
        public string HoraInicio { get; set; }
        public string HoraTermino { get; set; }
        public System.DateTime FechaActa { get; set; }
        public int IdRepresentanteEscu { get; set; }
        public int IdRepresentanteDepen { get; set; }
    }
}
