//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActaPresentacionAperturaProposiciones
    {
        public int Id { get; set; }
        public string HoraTermino { get; set; }
        public string Invitado1 { get; set; }
        public string Invitado2 { get; set; }
        public string Lugar { get; set; }
        public Nullable<int> TipoRepresentante { get; set; }
        public Nullable<int> Representante_Depen { get; set; }
        public Nullable<int> IdPaquete { get; set; }
    }
}
