//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContratosSevrEntities : DbContext
    {
        public ContratosSevrEntities()
            : base("name=ContratosSevrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contratistas> Contratistas { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<DescSostEsc> DescSostEsc { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Ejercicios> Ejercicios { get; set; }
        public virtual DbSet<Escuelas> Escuelas { get; set; }
        public virtual DbSet<EstadoBien> EstadoBien { get; set; }
        public virtual DbSet<ExperienciaAcreditada> ExperienciaAcreditada { get; set; }
        public virtual DbSet<Fundamentos> Fundamentos { get; set; }
        public virtual DbSet<LeyendaAnual> LeyendaAnual { get; set; }
        public virtual DbSet<Modalidades> Modalidades { get; set; }
        public virtual DbSet<ModalidadEsc> ModalidadEsc { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<NivelEsc> NivelEsc { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Recursos> Recursos { get; set; }
        public virtual DbSet<RepresentanteLegal> RepresentanteLegal { get; set; }
        public virtual DbSet<RolesSupervisores> RolesSupervisores { get; set; }
        public virtual DbSet<Supervisores> Supervisores { get; set; }
        public virtual DbSet<Tamanio> Tamanio { get; set; }
        public virtual DbSet<TipoInscripcion> TipoInscripcion { get; set; }
        public virtual DbSet<TipoPersona> TipoPersona { get; set; }
        public virtual DbSet<TiposEnagenacion> TiposEnagenacion { get; set; }
        public virtual DbSet<TipoServicio> TipoServicio { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
        public virtual DbSet<ContratistasInvitadosPaquete> ContratistasInvitadosPaquete { get; set; }
        public virtual DbSet<DetallePaquetesProyecto> DetallePaquetesProyecto { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<InvitacionCCP> InvitacionCCP { get; set; }
        public virtual DbSet<OficiosRecursos> OficiosRecursos { get; set; }
        public virtual DbSet<PaqProcedimiento> PaqProcedimiento { get; set; }
        public virtual DbSet<ProgramasContratacion> ProgramasContratacion { get; set; }
        public virtual DbSet<ProgramasRecursos> ProgramasRecursos { get; set; }
        public virtual DbSet<Proyectos> Proyectos { get; set; }
        public virtual DbSet<Entidades> Entidades { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
    }
}
