//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratistasInvitadosPaquete
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string Oficio { get; set; }
        public Nullable<System.DateTime> FechaOficio { get; set; }
        public int IdPequete { get; set; }
    
        public virtual Contratistas Contratistas { get; set; }
        public virtual PaqProcedimiento PaqProcedimiento { get; set; }
    }
}
