//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        public int Id { get; set; }
        public string no_contrato { get; set; }
        public string no_licitacion { get; set; }
        public string modalidad_contrato { get; set; }
        public Nullable<int> Contratista { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public Nullable<int> cve_encargado { get; set; }
        public string cve_escuela { get; set; }
        public string desc_obra { get; set; }
        public Nullable<decimal> monto_contrato { get; set; }
        public Nullable<decimal> anticipo { get; set; }
        public Nullable<decimal> monto_convenio { get; set; }
        public Nullable<decimal> monto_final_contrato { get; set; }
        public Nullable<int> recurso { get; set; }
        public Nullable<System.DateTime> FFirma { get; set; }
        public Nullable<System.DateTime> Inicia { get; set; }
        public Nullable<System.DateTime> termina { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaTerminoReal { get; set; }
        public Nullable<int> plazo_dias_nat { get; set; }
        public Nullable<int> plazo_conv { get; set; }
        public Nullable<int> plazo_final_cont { get; set; }
        public string cve_check_list { get; set; }
        public string obra { get; set; }
        public string TipoObra { get; set; }
        public string TipoAdquisicion { get; set; }
        public string no_expediente { get; set; }
        public string tomo { get; set; }
        public Nullable<decimal> av_prog { get; set; }
        public Nullable<decimal> av_fin { get; set; }
        public Nullable<decimal> av_fis { get; set; }
        public string observaciones { get; set; }
        public string Obra_Adquisicion { get; set; }
        public Nullable<int> Cve_Dep { get; set; }
        public string region { get; set; }
        public Nullable<decimal> PorcentajeAnticipo { get; set; }
        public string PerteneceCMIC { get; set; }
        public string NombreEcargado { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<int> IdDirectorGeneral { get; set; }
        public Nullable<int> Residente { get; set; }
        public Nullable<int> Superintendente { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdSector { get; set; }
        public Nullable<int> IdEstatu { get; set; }
        public string noCompFinanzasAnticipo { get; set; }
        public Nullable<int> Validar { get; set; }
        public string CURP { get; set; }
    }
}
