//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoObra
    {
        public int id { get; set; }
        public string no_contrato { get; set; }
        public string Anticipo { get; set; }
        public string Aportacion { get; set; }
        public string Articulo { get; set; }
        public string Cumplimiento { get; set; }
        public string ViciosOcultos { get; set; }
        public Nullable<int> cveArticulo { get; set; }
        public Nullable<System.DateTime> FechaProcedimiento { get; set; }
        public Nullable<int> Cambioarticulo { get; set; }
    }
}
