//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratistas()
        {
            this.ContratistasInvitadosPaquete = new HashSet<ContratistasInvitadosPaquete>();
            this.RepresentanteLegal = new HashSet<RepresentanteLegal>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string IMSS { get; set; }
        public string Infonavit { get; set; }
        public string FolioMercantilElectronico { get; set; }
        public string CMIC { get; set; }
        public string SIEM { get; set; }
        public string Domicilio { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Correo { get; set; }
        public Nullable<decimal> CapitalContable { get; set; }
        public Nullable<decimal> CapitalSocial { get; set; }
        public string ActaNumEscritura { get; set; }
        public string ActaVolumenEscritura { get; set; }
        public Nullable<System.DateTime> ActaFechaConstancia { get; set; }
        public string NumNotaria { get; set; }
        public string CiudadNotaria { get; set; }
        public string Modalidad { get; set; }
        public string NombreTitularNotaria { get; set; }
        public string NombreAdscrito { get; set; }
        public string DireccionNoraria { get; set; }
        public string NumRPPC { get; set; }
        public string VolRPPC { get; set; }
        public Nullable<System.DateTime> FechaRPPC { get; set; }
        public string CiudadRppc { get; set; }
        public string Folios { get; set; }
        public string LibroNum { get; set; }
        public string NumActaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaActaNacimiento { get; set; }
        public string LugarExpedicion { get; set; }
        public string LibroActanacimiento { get; set; }
        public int IdTamaño { get; set; }
        public int IdTipoInscripcion { get; set; }
        public int IdTipoPersona { get; set; }
        public int IdTipoServicio { get; set; }
        public string ClaveRegistro { get; set; }
        public System.DateTime FechaInicioVigencia { get; set; }
        public System.DateTime FechaTerminoVigencia { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> Registro { get; set; }
        public Nullable<int> Reviso { get; set; }
        public Nullable<int> VoBo { get; set; }
        public Nullable<int> Autorizo { get; set; }
        public Nullable<short> EstatusCaptura { get; set; }
        public int IdExperiencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratistasInvitadosPaquete> ContratistasInvitadosPaquete { get; set; }
        public virtual ExperienciaAcreditada ExperienciaAcreditada { get; set; }
        public virtual Entidades Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepresentanteLegal> RepresentanteLegal { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Tamanio Tamanio { get; set; }
        public virtual TipoInscripcion TipoInscripcion { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
