//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratistasProgramaContratacion
    {
        public int id { get; set; }
        public Nullable<int> idContratista { get; set; }
        public string Oficio { get; set; }
        public Nullable<System.DateTime> FechaOficio { get; set; }
        public Nullable<int> IdPaquete { get; set; }
    
        public virtual PaquetesProcedimiento PaquetesProcedimiento { get; set; }
    }
}
