//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC
    {
        public int Clave { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Cargo { get; set; }
        public string Direccion_Particular { get; set; }
        public string Cedula_Prof { get; set; }
        public string Municipio { get; set; }
        public string Tel_Partic { get; set; }
        public string Nombre_Supervis_Pertenece { get; set; }
        public Nullable<int> dependencia { get; set; }
        public string rfc { get; set; }
        public string SEXO { get; set; }
        public Nullable<int> id_departamento { get; set; }
    }
}
