//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOficiosProyecto
    {
        public int Id { get; set; }
        public int IdDetalleOficiosRecurso { get; set; }
        public int IdProyecto { get; set; }
    
        public virtual DetalleOficiosRecurso DetalleOficiosRecurso { get; set; }
        public virtual ESCU ESCU { get; set; }
    }
}
