//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Contratista
    {
        public int Id { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Contrato { get; set; }
        public Nullable<int> Clave { get; set; }
        public Nullable<int> Clave_Documento { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdEmpresaRepLegal { get; set; }
        public string TipoNotarioEmpresa { get; set; }
        public string TipoNotarioRepLegal { get; set; }
        public string ElLa { get; set; }
        public Nullable<decimal> PorcentajeActividadesContrato { get; set; }
        public Nullable<decimal> ImporteAPagar { get; set; }
        public Nullable<System.DateTime> InicioActividades { get; set; }
        public Nullable<System.DateTime> TerminoActividades { get; set; }
        public string DescripcionTrabajos { get; set; }
        public Nullable<int> RepresentanteComun { get; set; }
        public Nullable<int> Proyecto { get; set; }
    }
}
