//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePaquetesProyecto
    {
        public int Id { get; set; }
        public int IdPaquete { get; set; }
        public int IdProyecto { get; set; }
        public Nullable<int> PlazoEjecucion { get; set; }
        public Nullable<decimal> Anticipo { get; set; }
        public Nullable<decimal> ImporteAutoruizado { get; set; }
        public Nullable<decimal> CapitalContable { get; set; }
        public Nullable<int> IdResidente { get; set; }
        public Nullable<decimal> ImportePresupuestoBase { get; set; }
    
        public virtual Supervisores Supervisores { get; set; }
        public virtual PaqProcedimiento PaqProcedimiento { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
