//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePaqueteProyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallePaqueteProyecto()
        {
            this.DetalleImporteProyectoLicitante = new HashSet<DetalleImporteProyectoLicitante>();
        }
    
        public int Id { get; set; }
        public int IdPaquete { get; set; }
        public int IdProyecto { get; set; }
        public Nullable<int> PlazoEjecucion { get; set; }
        public Nullable<int> Anticipo { get; set; }
        public Nullable<decimal> ImporteAutorizado { get; set; }
        public Nullable<decimal> CapitalContable { get; set; }
        public Nullable<int> Residente { get; set; }
        public Nullable<decimal> ImportePresupuestoBase { get; set; }
    
        public virtual ESCU ESCU { get; set; }
        public virtual PaquetesProcedimiento PaquetesProcedimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleImporteProyectoLicitante> DetalleImporteProyectoLicitante { get; set; }
    }
}
