//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_CcpDesignacion
    {
        public int Id { get; set; }
        public Nullable<int> Numero { get; set; }
        public string nombre_ccp { get; set; }
        public string pueto_ccp { get; set; }
        public string contrato { get; set; }
        public Nullable<int> Clave_documento { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string TipoDe { get; set; }
    }
}
