//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMemo
    {
        public int ID { get; set; }
        public Nullable<int> Para { get; set; }
        public Nullable<System.DateTime> FechaCreacionMemo { get; set; }
        public string Anexos { get; set; }
        public Nullable<int> Atentamente { get; set; }
        public Nullable<int> ATN { get; set; }
        public string VoBo { get; set; }
        public string MEMO { get; set; }
    }
}
