//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleImporteProyectoLicitante
    {
        public int Id { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> IdContratista { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> IdDetallePaqueteProyecto { get; set; }
    
        public virtual DetallePaqueteProyecto DetallePaqueteProyecto { get; set; }
    }
}
