//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictamen
    {
        public int Id { get; set; }
        public string PaqueteDescripcion { get; set; }
        public Nullable<int> Elaboro { get; set; }
        public Nullable<int> Reviso { get; set; }
        public Nullable<int> Aprobo { get; set; }
        public Nullable<int> IdPaquete { get; set; }
    }
}
