//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS
    {
        public int Clave { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public string CURP { get; set; }
        public string Imss { get; set; }
        public string Infonavit { get; set; }
        public string FolioMercantilElectronico { get; set; }
        public string Cmic { get; set; }
        public string Domicilio { get; set; }
        public string No_Ext { get; set; }
        public string No_Int { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Ac_NumEsc { get; set; }
        public string Ac_VolEsc { get; set; }
        public Nullable<System.DateTime> Ac_FechaEsc { get; set; }
        public string Ac_NumNot { get; set; }
        public string Ac_NombreNot { get; set; }
        public string Ac_ResidNot { get; set; }
        public string Ac_NumRPPC { get; set; }
        public string Ac_VolRPPC { get; set; }
        public Nullable<System.DateTime> Ac_FechaRPPC { get; set; }
        public string Ac_CiudadRPPC { get; set; }
        public string Nom_Socio1 { get; set; }
        public Nullable<decimal> Porc_Socio1 { get; set; }
        public string Nom_Socio2 { get; set; }
        public Nullable<decimal> Porc_Socio2 { get; set; }
        public string Nom_Socio3 { get; set; }
        public Nullable<decimal> Porc_Socio3 { get; set; }
        public string Nom_Socio4 { get; set; }
        public Nullable<decimal> Porc_Socio4 { get; set; }
        public string Nom_Socio5 { get; set; }
        public Nullable<decimal> Porc_Socio5 { get; set; }
        public string Nom_Socio6 { get; set; }
        public Nullable<decimal> Porc_Socio6 { get; set; }
        public string Nom_Socio7 { get; set; }
        public Nullable<decimal> Porc_Socio7 { get; set; }
        public string Nom_Socio8 { get; set; }
        public Nullable<decimal> Porc_Socio8 { get; set; }
        public string Nom_Socio9 { get; set; }
        public Nullable<decimal> Porc_Socio9 { get; set; }
        public string Nom_Socio10 { get; set; }
        public Nullable<decimal> Porc_Socio10 { get; set; }
        public string NoActaNac { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string LugNac { get; set; }
        public string PF_FolioElect { get; set; }
        public string PF_Calle { get; set; }
        public string PF_Num { get; set; }
        public string PF_Colonia { get; set; }
        public string PF_CodigoPostal { get; set; }
        public string PF_Ciudad { get; set; }
        public string PF_Telefono { get; set; }
        public string PF_Celular { get; set; }
        public string PF_Email { get; set; }
        public string tipo { get; set; }
        public string TipoPer { get; set; }
        public string Password { get; set; }
        public string RepLegal { get; set; }
        public string Puesto { get; set; }
        public string Cred_Elecrl { get; set; }
        public string Rl_numesc { get; set; }
        public string Rl_volesc { get; set; }
        public Nullable<System.DateTime> Rl_fechaesc { get; set; }
        public string Rl_numnot { get; set; }
        public string Rl_nombrenot { get; set; }
        public string Rl_residnot { get; set; }
        public string Rl_numrppc { get; set; }
        public string Rl_volrppc { get; set; }
        public Nullable<System.DateTime> Rl_fecharppc { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string LugReg { get; set; }
        public Nullable<decimal> CapitalSocial { get; set; }
        public Nullable<decimal> CapitalContable { get; set; }
        public string PadronContra { get; set; }
        public string Adscrito_o_Titular { get; set; }
        public string LugExpActa { get; set; }
        public string LibroAsentado { get; set; }
        public string LibroNot { get; set; }
        public string Folios { get; set; }
        public string LugNot { get; set; }
        public string TipoPersona { get; set; }
        public string NomAdscrito { get; set; }
        public string NomSubstituto { get; set; }
        public string Tomo { get; set; }
        public string ClaveRegistro { get; set; }
        public Nullable<System.DateTime> FechaInicioVigencia { get; set; }
        public Nullable<System.DateTime> FechaTerminoVigencia { get; set; }
        public Nullable<int> Clasificacion { get; set; }
        public Nullable<int> TipoInscripcion { get; set; }
        public string Siem { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> Registro { get; set; }
        public Nullable<int> Reviso { get; set; }
        public Nullable<int> VoBo { get; set; }
        public Nullable<int> Autorizo { get; set; }
        public Nullable<System.DateTime> FechaElaboracion { get; set; }
        public string TipoSeleccion { get; set; }
        public string Padron { get; set; }
        public string Localidad { get; set; }
    }
}
