//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuelas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escuelas()
        {
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public int Id { get; set; }
        public int IdNivel { get; set; }
        public int IdModalidad { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Sector { get; set; }
        public string Zona { get; set; }
        public string Domicilio { get; set; }
        public int Localidad { get; set; }
        public int DescSost { get; set; }
        public string ClaveLocalidad { get; set; }
    
        public virtual DescSostEsc DescSostEsc { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual ModalidadEsc ModalidadEsc { get; set; }
        public virtual NivelEsc NivelEsc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
