//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESCU()
        {
            this.DetalleOficiosProyecto = new HashSet<DetalleOficiosProyecto>();
            this.DetallePaqueteProyecto = new HashSet<DetallePaqueteProyecto>();
        }
    
        public int id { get; set; }
        public string CCT_TURNO { get; set; }
        public string NOMESC { get; set; }
        public Nullable<int> Cve_Localidad { get; set; }
        public Nullable<int> Cve_Nivel { get; set; }
        public string CVETUR { get; set; }
        public string SECTOR { get; set; }
        public string DIRESC { get; set; }
        public string CP { get; set; }
        public Nullable<decimal> importe_autorizado { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> ClaveRecurso { get; set; }
        public string ClaveEscuela { get; set; }
        public Nullable<System.DateTime> FechaAviso { get; set; }
        public string NOMDIR { get; set; }
        public string SE { get; set; }
        public string TELEFONO { get; set; }
        public string E_Mail { get; set; }
        public string municipio { get; set; }
        public Nullable<int> Dependencia { get; set; }
        public Nullable<int> ClaveFF { get; set; }
        public string ObservacionEstimaciones { get; set; }
        public Nullable<int> Obra { get; set; }
        public Nullable<int> Aula { get; set; }
        public Nullable<int> Laboratorio { get; set; }
        public Nullable<int> Talleres { get; set; }
        public Nullable<int> Anexos { get; set; }
        public Nullable<int> EspaciosEducativos { get; set; }
        public Nullable<int> Local { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> CantAlumnos { get; set; }
        public Nullable<int> EmpleosGen { get; set; }
        public string Recurso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOficiosProyecto> DetalleOficiosProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePaqueteProyecto> DetallePaqueteProyecto { get; set; }
    }
}
