//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fallo
    {
        public int id { get; set; }
        public Nullable<int> Invitado1 { get; set; }
        public Nullable<int> Invitado2 { get; set; }
        public Nullable<int> Invitado3 { get; set; }
        public Nullable<System.DateTime> PeriodoFianza { get; set; }
        public string HoraFianza { get; set; }
        public Nullable<System.DateTime> FechadeContratacion { get; set; }
        public Nullable<System.DateTime> FechaCita { get; set; }
        public string HoraCita { get; set; }
        public string HoraTermino { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public string Obra_Adquisicion_Servicio { get; set; }
        public string PerteneceCMIC { get; set; }
        public string GarantiaCumplimiento { get; set; }
        public string GarantiaViciosOcultos { get; set; }
        public string Notas { get; set; }
    }
}
