//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FalloProyecto
    {
        public int id { get; set; }
        public string No_Contrato { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Contratista { get; set; }
        public Nullable<decimal> ImporteAnticipo { get; set; }
        public Nullable<int> IdDetallePaqueteProyecto { get; set; }
        public string Desc_obra { get; set; }
        public Nullable<int> IVA { get; set; }
    }
}
