//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneradorContrato
    {
        public int Id { get; set; }
        public string NumeroContrato { get; set; }
        public string OficioNumero { get; set; }
        public string FechaAutoriza { get; set; }
        public string Articulo { get; set; }
        public string NumeroExhibicion { get; set; }
        public string ExhibicionDependencia { get; set; }
        public string ExhibicionUbicacion { get; set; }
        public string Dependencia1 { get; set; }
        public string Dependencia2 { get; set; }
        public string EstimacionDependencia { get; set; }
        public string EstimacionUbicacion { get; set; }
        public Nullable<System.DateTime> FechaConformidad { get; set; }
        public string Testigo1 { get; set; }
        public string Cargo1 { get; set; }
        public string Testigo2 { get; set; }
        public string Cargo2 { get; set; }
        public string Testigo3 { get; set; }
        public string Cargo3 { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Partida { get; set; }
        public Nullable<decimal> MontoAutorizado { get; set; }
        public Nullable<System.DateTime> FechaProcedimiento { get; set; }
        public string Anticipo { get; set; }
        public string NotarioC { get; set; }
        public string NotarioR { get; set; }
        public Nullable<System.DateTime> FechaAviso { get; set; }
        public string Inversion { get; set; }
        public string FacturadoA { get; set; }
        public string DomicilioFactura { get; set; }
        public string RFCFactura { get; set; }
        public string CiudadFactura { get; set; }
        public string CPFactura { get; set; }
        public string EntregadeBienes { get; set; }
        public string Anexos { get; set; }
        public string SupervisorContrato { get; set; }
        public Nullable<int> Ejemplares { get; set; }
        public string Encabezado1 { get; set; }
        public string Encabezado2 { get; set; }
        public string Encabezado3 { get; set; }
        public string Encabezado4 { get; set; }
        public Nullable<System.DateTime> FechaConvenioAgrupacion { get; set; }
    }
}
