//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public string NombreBien { get; set; }
        public string Marca { get; set; }
        public string Tipo { get; set; }
        public string Serie { get; set; }
        public string Modelo { get; set; }
        public int IdEstadoBien { get; set; }
        public int IdUbicacion { get; set; }
        public int IdDireccion { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<decimal> ValorFacturado { get; set; }
        public Nullable<decimal> ValorActual { get; set; }
        public int IdPersonal { get; set; }
        public int IdTipoEnagenacion { get; set; }
        public string Caracteristicas { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Direcciones Direcciones { get; set; }
        public virtual EstadoBien EstadoBien { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TiposEnagenacion TiposEnagenacion { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
