//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Localidades()
        {
            this.Escuelas = new HashSet<Escuelas>();
        }
    
        public int id { get; set; }
        public short idEntidad { get; set; }
        public short idPais { get; set; }
        public string nombre { get; set; }
        public decimal x { get; set; }
        public decimal y { get; set; }
        public byte exacto { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public string CP { get; set; }
        public string Clave1Localidad { get; set; }
        public string Clave2Localidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Escuelas> Escuelas { get; set; }
        public virtual Municipios Municipios { get; set; }
    }
}
