//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OficiosRecursos
    {
        public int IdOficio { get; set; }
        public string Oficio { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdRecurso { get; set; }
        public decimal ImporteAutorizado { get; set; }
        public string Ubicacion { get; set; }
        public string Archivo { get; set; }
        public string IdUsusario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Emisora { get; set; }
    
        public virtual ProgramasRecursos ProgramasRecursos { get; set; }
    }
}
