//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetesProcedimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaquetesProcedimiento()
        {
            this.ContratistasProgramaContratacion = new HashSet<ContratistasProgramaContratacion>();
            this.DetallePaqueteProyecto = new HashSet<DetallePaqueteProyecto>();
            this.ProgramaDeContratacion = new HashSet<ProgramaDeContratacion>();
        }
    
        public int idPaquete { get; set; }
        public Nullable<int> Paquete { get; set; }
        public Nullable<int> Proyecto { get; set; }
        public string NoProcedimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fchConvocatoria { get; set; }
        public Nullable<System.DateTime> fchLimiteInscripcion { get; set; }
        public Nullable<System.DateTime> fchVisitaSitio { get; set; }
        public Nullable<System.DateTime> fchJuntaAclaracion { get; set; }
        public Nullable<System.DateTime> fchAperturaTecnicaEconomica { get; set; }
        public Nullable<System.DateTime> fchFallo { get; set; }
        public Nullable<System.DateTime> fchContrato { get; set; }
        public string hrLimiteInscripcion { get; set; }
        public string hrVisitaSitio { get; set; }
        public string hrJuntaAclaracion { get; set; }
        public string hrAperturaTecnicaEconomica { get; set; }
        public string hrFallo { get; set; }
        public string hrContrato { get; set; }
        public Nullable<System.DateTime> FechaInicioEstimada { get; set; }
        public Nullable<int> Residente { get; set; }
        public Nullable<decimal> Recuperacion { get; set; }
        public Nullable<decimal> ImportePresupuestoBase { get; set; }
        public Nullable<int> Anio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratistasProgramaContratacion> ContratistasProgramaContratacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePaqueteProyecto> DetallePaqueteProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaDeContratacion> ProgramaDeContratacion { get; set; }
    }
}
