//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Inventario = new HashSet<Inventario>();
            this.ProgramasContratacion = new HashSet<ProgramasContratacion>();
            this.ProgramasContratacion1 = new HashSet<ProgramasContratacion>();
            this.ProgramasContratacion2 = new HashSet<ProgramasContratacion>();
            this.ProgramasContratacion3 = new HashSet<ProgramasContratacion>();
            this.ProgramasContratacion4 = new HashSet<ProgramasContratacion>();
        }
    
        public int Id { get; set; }
        public string Trato { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int IdDireccion { get; set; }
        public string Cargo { get; set; }
        public string Domicilio { get; set; }
        public string RFC { get; set; }
        public int IdDepartamento { get; set; }
        public bool Sexo { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Estatus { get; set; }
        public Nullable<int> IdJefeInmediato { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Direcciones Direcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramasContratacion> ProgramasContratacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramasContratacion> ProgramasContratacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramasContratacion> ProgramasContratacion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramasContratacion> ProgramasContratacion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramasContratacion> ProgramasContratacion4 { get; set; }
    }
}
