//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGO
    {
        public int Clave { get; set; }
        public Nullable<int> INVERSIONE { get; set; }
        public Nullable<int> INVERSIONF { get; set; }
        public string DESCRIPCION { get; set; }
        public string AUTORIZACION { get; set; }
        public string APROBACION { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<decimal> Monto_Autorizado { get; set; }
        public Nullable<System.DateTime> FechaOficio { get; set; }
        public string No_Oficio { get; set; }
        public Nullable<decimal> aportacion_municipal { get; set; }
        public string Programa { get; set; }
        public string ClaveFF { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Procedencia { get; set; }
        public string Recurso { get; set; }
        public string Nivel { get; set; }
    }
}
