//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasActaVisita
    {
        public int idPregunta { get; set; }
        public Nullable<int> no_contratista { get; set; }
        public Nullable<int> no_pregunta { get; set; }
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> IdPaquete { get; set; }
    }
}
