//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramasContratacion
    {
        public int Id { get; set; }
        public Nullable<int> IdDirector { get; set; }
        public Nullable<short> ClaveArticulo { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> IdDirectorFirma { get; set; }
        public string TIpoInversion { get; set; }
        public Nullable<int> IdModalidad { get; set; }
        public Nullable<int> IdVoBo { get; set; }
        public Nullable<int> IdReviso { get; set; }
        public Nullable<int> IdAutorizo { get; set; }
        public Nullable<System.DateTime> FechaOficio { get; set; }
        public string TxtVoBo { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public Nullable<int> IdExperienciaAcreditada { get; set; }
    
        public virtual ExperienciaAcreditada ExperienciaAcreditada { get; set; }
        public virtual Modalidades Modalidades { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
        public virtual Personal Personal2 { get; set; }
        public virtual Personal Personal3 { get; set; }
        public virtual Personal Personal4 { get; set; }
        public virtual PaqProcedimiento PaqProcedimiento { get; set; }
    }
}
