//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramasRecursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramasRecursos()
        {
            this.OficiosRecursos = new HashSet<OficiosRecursos>();
        }
    
        public int IdProgramasRecursos { get; set; }
        public int Ejercicio { get; set; }
        public Nullable<float> Inversion_Est { get; set; }
        public Nullable<float> Inversion_Fed { get; set; }
        public Nullable<decimal> Inversion_Mun { get; set; }
        public Nullable<decimal> MontoAutorizado { get; set; }
        public string ClaveFuenteFin { get; set; }
        public string Descripcion { get; set; }
        public string Procedencia { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string IDUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public byte IdNivel { get; set; }
        public int IdRecurso { get; set; }
    
        public virtual Ejercicios Ejercicios { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual Recursos Recursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OficiosRecursos> OficiosRecursos { get; set; }
    }
}
