//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaDeContratacion
    {
        public int id { get; set; }
        public Nullable<int> Director { get; set; }
        public Nullable<int> cveArticulo { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> DirectorFirma { get; set; }
        public string TipoInversion { get; set; }
        public Nullable<int> Modalidad { get; set; }
        public Nullable<int> VoBo { get; set; }
        public Nullable<int> Reviso { get; set; }
        public Nullable<int> Autorizo { get; set; }
        public Nullable<System.DateTime> Fechaoficio { get; set; }
        public string txtVoBo { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public Nullable<int> Fraccion { get; set; }
        public string Metas { get; set; }
        public Nullable<int> idExperienciaAcreditada { get; set; }
    
        public virtual PaquetesProcedimiento PaquetesProcedimiento { get; set; }
    }
}
