//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.DetallePaquetesProyecto = new HashSet<DetallePaquetesProyecto>();
            this.PaqProcedimiento = new HashSet<PaqProcedimiento>();
        }
    
        public int Id { get; set; }
        public string ClaveProyecto { get; set; }
        public decimal ImporteEutorizado { get; set; }
        public decimal Anticipo { get; set; }
        public int IdProgramadeRecursos { get; set; }
        public int IdEscuela { get; set; }
        public Nullable<int> EmpleosGenerador { get; set; }
        public Nullable<int> AlumnosBeneficiados { get; set; }
        public Nullable<System.DateTime> FechaAviso { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> IdRecidente { get; set; }
        public Nullable<int> IdSupervisor { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Escuelas Escuelas { get; set; }
        public virtual RolesSupervisores RolesSupervisores { get; set; }
        public virtual Supervisores Supervisores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePaquetesProyecto> DetallePaquetesProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaqProcedimiento> PaqProcedimiento { get; set; }
    }
}
