//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_LEGA
    {
        public int CONSEC { get; set; }
        public Nullable<int> CLAVE { get; set; }
        public string REPLEGAL { get; set; }
        public string PUESTO { get; set; }
        public string FOLIOELECT { get; set; }
        public string RFC { get; set; }
        public string FolioMercantilElectronico { get; set; }
        public string CALLE { get; set; }
        public string NUM { get; set; }
        public string COLONIA { get; set; }
        public string CODIGOPOSTAL { get; set; }
        public string CIUDAD { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string NUMESC { get; set; }
        public string VOLESC { get; set; }
        public Nullable<System.DateTime> FECHAESC { get; set; }
        public string NUMNOT { get; set; }
        public string NOMBRENOT { get; set; }
        public string RESIDNOT { get; set; }
        public string NUMRPPC { get; set; }
        public string VOLRPPC { get; set; }
        public Nullable<System.DateTime> FECHARPPC { get; set; }
        public string CIUDADRPPC { get; set; }
        public string NoActaNac { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string LugExpActa { get; set; }
        public string LibroAsentado { get; set; }
        public string Folios { get; set; }
        public string LugNot { get; set; }
        public string LibroNot { get; set; }
        public string NomAdscritoR { get; set; }
        public string NomSubstitutoR { get; set; }
        public string Tomo { get; set; }
    }
}
