//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresentanteLegal
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public string FolioElectoral { get; set; }
        public string RFC { get; set; }
        public string FolioMercantilElectronico { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string NumEscritura { get; set; }
        public string VolEscritura { get; set; }
        public Nullable<System.DateTime> FechaEscritura { get; set; }
        public string NumNotario { get; set; }
        public string NombreNotario { get; set; }
        public string LugarNotario { get; set; }
        public string NumRPPC { get; set; }
        public string VolRPPC { get; set; }
        public Nullable<System.DateTime> FechaRPPC { get; set; }
        public string LugarRPPC { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string LugarExpedicionActa { get; set; }
        public string NombreAdscrito { get; set; }
        public string NombreSustituto { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual Contratistas Contratistas { get; set; }
    }
}
