//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sicop_tempEntities : DbContext
    {
        public sicop_tempEntities()
            : base("name=sicop_tempEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActaAperturaEconomica> ActaAperturaEconomica { get; set; }
        public virtual DbSet<ActaJuntaAclaracion> ActaJuntaAclaracion { get; set; }
        public virtual DbSet<CatalogoExperienciaAcreditada> CatalogoExperienciaAcreditada { get; set; }
        public virtual DbSet<CatalogoSeguimientoEstimacion> CatalogoSeguimientoEstimacion { get; set; }
        public virtual DbSet<checklist> checklist { get; set; }
        public virtual DbSet<ConceptosAdjudicacion> ConceptosAdjudicacion { get; set; }
        public virtual DbSet<ContratistasActas> ContratistasActas { get; set; }
        public virtual DbSet<ContratistasProgramaContratacion> ContratistasProgramaContratacion { get; set; }
        public virtual DbSet<ContratoObra> ContratoObra { get; set; }
        public virtual DbSet<contratos> contratos { get; set; }
        public virtual DbSet<CuentaPartida> CuentaPartida { get; set; }
        public virtual DbSet<DC> DC { get; set; }
        public virtual DbSet<Detalle_CcpDesignacion> Detalle_CcpDesignacion { get; set; }
        public virtual DbSet<Detalle_Proyectos> Detalle_Proyectos { get; set; }
        public virtual DbSet<DetalleAclaraciones> DetalleAclaraciones { get; set; }
        public virtual DbSet<DetalleMemo> DetalleMemo { get; set; }
        public virtual DbSet<DetalleOficiosProyecto> DetalleOficiosProyecto { get; set; }
        public virtual DbSet<DetalleOficiosRecurso> DetalleOficiosRecurso { get; set; }
        public virtual DbSet<DetallePaqueteProyecto> DetallePaqueteProyecto { get; set; }
        public virtual DbSet<DetalleRubricas> DetalleRubricas { get; set; }
        public virtual DbSet<EMPRESAS> EMPRESAS { get; set; }
        public virtual DbSet<ESCU> ESCU { get; set; }
        public virtual DbSet<GeneradorContrato> GeneradorContrato { get; set; }
        public virtual DbSet<Leyendas> Leyendas { get; set; }
        public virtual DbSet<Modalidad> Modalidad { get; set; }
        public virtual DbSet<NOTASACTAAPERTURA> NOTASACTAAPERTURA { get; set; }
        public virtual DbSet<ProgramaDeContratacion> ProgramaDeContratacion { get; set; }
        public virtual DbSet<ProyectosEnContrato> ProyectosEnContrato { get; set; }
        public virtual DbSet<SeguimientoEstimacion> SeguimientoEstimacion { get; set; }
        public virtual DbSet<PGO> PGO { get; set; }
        public virtual DbSet<VwAperturaTecnica> VwAperturaTecnica { get; set; }
        public virtual DbSet<vwContratos> vwContratos { get; set; }
        public virtual DbSet<VwContratosProg> VwContratosProg { get; set; }
        public virtual DbSet<VwFallos> VwFallos { get; set; }
        public virtual DbSet<VwInvitacion1> VwInvitacion1 { get; set; }
        public virtual DbSet<VwJuntaAclaraciones> VwJuntaAclaraciones { get; set; }
        public virtual DbSet<vwPaqInvitados> vwPaqInvitados { get; set; }
        public virtual DbSet<VwProgramaCont> VwProgramaCont { get; set; }
        public virtual DbSet<vwRecursosEnContrato> vwRecursosEnContrato { get; set; }
        public virtual DbSet<VwReporteContrato> VwReporteContrato { get; set; }
        public virtual DbSet<vwReportesContratoAdq> vwReportesContratoAdq { get; set; }
        public virtual DbSet<PaquetesProcedimiento> PaquetesProcedimiento { get; set; }
        public virtual DbSet<SUPERVIS> SUPERVIS { get; set; }
        public virtual DbSet<InvitadosActas> InvitadosActas { get; set; }
        public virtual DbSet<PreguntasActaVisita> PreguntasActaVisita { get; set; }
        public virtual DbSet<ControlInvitadosActas> ControlInvitadosActas { get; set; }
        public virtual DbSet<DetalleImporteProyectoLicitante> DetalleImporteProyectoLicitante { get; set; }
        public virtual DbSet<ActaPresentacionAperturaProposiciones> ActaPresentacionAperturaProposiciones { get; set; }
        public virtual DbSet<CatalogoAclaracion3> CatalogoAclaracion3 { get; set; }
        public virtual DbSet<FalloProyecto> FalloProyecto { get; set; }
        public virtual DbSet<Fallo> Fallo { get; set; }
        public virtual DbSet<VwReporteCaratula> VwReporteCaratula { get; set; }
        public virtual DbSet<vwReporteCaratulaAdq> vwReporteCaratulaAdq { get; set; }
        public virtual DbSet<Detalle_Contratista> Detalle_Contratista { get; set; }
        public virtual DbSet<REP_LEGA> REP_LEGA { get; set; }
        public virtual DbSet<Dictamen> Dictamen { get; set; }
    }
}
