//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwContratos
    {
        public int Id_Contrato { get; set; }
        public string no_contrato { get; set; }
        public string proyecto { get; set; }
        public Nullable<int> INVERSIONE { get; set; }
        public Nullable<int> INVERSIONF { get; set; }
        public Nullable<int> ANIO { get; set; }
        public string programa { get; set; }
        public string obra { get; set; }
        public string DescObra { get; set; }
        public Nullable<decimal> monto_contrato { get; set; }
        public Nullable<decimal> anticipo { get; set; }
        public Nullable<decimal> monto_convenio { get; set; }
        public string TipoObra { get; set; }
        public string Obra_Adquisicion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaTerminoReal { get; set; }
        public Nullable<int> dias { get; set; }
        public string No_Oficio { get; set; }
        public Nullable<System.DateTime> fechaOficio { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public string Domicilio { get; set; }
        public string ClaveRegistro { get; set; }
        public string Imss { get; set; }
        public string Infonavit { get; set; }
        public string oficio_inv { get; set; }
        public string DirectorSupervision { get; set; }
        public Nullable<int> clave_DirectorSupervision { get; set; }
        public string Superintendente { get; set; }
        public Nullable<int> clave_Superintendente { get; set; }
        public string RevisorEstimaciones { get; set; }
        public Nullable<int> clave_RevisorEstimaciones { get; set; }
        public string JefeZona { get; set; }
        public Nullable<int> clave_JefeZona { get; set; }
        public string Residente { get; set; }
        public Nullable<int> clave_residente { get; set; }
        public string CCT { get; set; }
        public string plantel { get; set; }
        public string NIVEL { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public string Entidad { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> FFirma { get; set; }
    }
}
