//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwContratosProg
    {
        public int Id { get; set; }
        public string Proyecto { get; set; }
        public Nullable<int> Paquete { get; set; }
        public string DESCRIPCION { get; set; }
        public string CCT_TURNO { get; set; }
        public string nivel { get; set; }
        public string CCT { get; set; }
        public string nivel2 { get; set; }
        public string NombreEscuela { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public Nullable<int> plazoejecucion { get; set; }
        public string descripcion_LUZ { get; set; }
        public string descripcion2 { get; set; }
        public Nullable<decimal> inversionAutorizada { get; set; }
        public Nullable<decimal> CapitalContable { get; set; }
        public Nullable<decimal> ImportePresupuestoBase { get; set; }
        public string NoProcedimiento { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<int> Anticipo { get; set; }
        public string Oficio { get; set; }
        public string ClaveFF { get; set; }
        public Nullable<System.DateTime> fechaInvitacion { get; set; }
        public Nullable<System.DateTime> fchLimiteInscripcion { get; set; }
        public Nullable<decimal> bases { get; set; }
        public Nullable<System.DateTime> fecha_visita { get; set; }
        public string hrVisitaSitio { get; set; }
        public Nullable<System.DateTime> fchJuntaAclaracion { get; set; }
        public string horaJuntadeaclaraciones { get; set; }
        public Nullable<System.DateTime> fchAperturaTecnicaEconomica { get; set; }
        public string hrAperturaTecnicaEconomica { get; set; }
        public Nullable<System.DateTime> fchFallo { get; set; }
        public string hrFallo { get; set; }
        public Nullable<System.DateTime> fchContrato { get; set; }
        public string hrContrato { get; set; }
        public Nullable<int> plazo_dias_nat { get; set; }
        public Nullable<System.DateTime> Inicia { get; set; }
        public Nullable<System.DateTime> termina { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string autoriza { get; set; }
        public Nullable<decimal> ImporteAutorizado { get; set; }
        public Nullable<decimal> Presupuestobasesiniva { get; set; }
    }
}
