//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvitacion1
    {
        public Nullable<int> id { get; set; }
        public int idPaquete { get; set; }
        public string Oficio { get; set; }
        public int Clave { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaOficio { get; set; }
        public string TipoPersona { get; set; }
        public string Padron { get; set; }
        public string REPLEGAL { get; set; }
        public string PUESTO { get; set; }
        public string modalidad { get; set; }
        public string Articulo { get; set; }
        public string NoProcedimiento { get; set; }
        public string paquete { get; set; }
        public Nullable<System.DateTime> fchVisitaSitio { get; set; }
        public string hrVisitaSitio { get; set; }
        public Nullable<System.DateTime> fchJuntaAclaracion { get; set; }
        public string hrJuntaAclaracion { get; set; }
        public Nullable<System.DateTime> fchAperturaTecnicaEconomica { get; set; }
        public string hrAperturaTecnicaEconomica { get; set; }
        public Nullable<System.DateTime> FechaInicioEstimada { get; set; }
        public Nullable<System.DateTime> fchLimiteInscripcion { get; set; }
        public string hrLimiteInscripcion { get; set; }
        public Nullable<decimal> CapitalContable { get; set; }
        public Nullable<int> Anticipo { get; set; }
        public string descobra { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public Nullable<int> PlazoEjecucion { get; set; }
        public string Director { get; set; }
        public string Direccion { get; set; }
        public string Cargo { get; set; }
        public string firmanombre { get; set; }
        public string firmacargo { get; set; }
        public string direccioncargo { get; set; }
        public string txtVoBo { get; set; }
        public string ExpAcred { get; set; }
        public Nullable<decimal> Recuperacion { get; set; }
        public Nullable<int> ejercicio { get; set; }
        public Nullable<int> NumPaquete { get; set; }
        public string Proyecto { get; set; }
    }
}
