//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwJuntaAclaraciones
    {
        public int idContratistasActas { get; set; }
        public int idPaquete { get; set; }
        public string Modalidad { get; set; }
        public string NoProcedimiento { get; set; }
        public Nullable<int> Paquete { get; set; }
        public string NumPaquete { get; set; }
        public string DescTrabajos { get; set; }
        public Nullable<System.DateTime> fechajunta { get; set; }
        public string hrjunta { get; set; }
        public string DescObra { get; set; }
        public string empresa { get; set; }
        public string RepDependencia { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string HoraTermino { get; set; }
        public string director { get; set; }
        public string CargoDirector { get; set; }
        public string invitado1 { get; set; }
        public string cargoinv1 { get; set; }
        public string NOMBRE { get; set; }
        public string Asistente { get; set; }
        public Nullable<int> No_Preguntas { get; set; }
        public Nullable<int> Ejercicio { get; set; }
        public Nullable<int> NoActa { get; set; }
        public Nullable<int> IdActa { get; set; }
        public string inv3 { get; set; }
        public string cargoinv3 { get; set; }
    }
}
