//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaqInvitados
    {
        public int id { get; set; }
        public string Proyecto { get; set; }
        public int IdPaquete { get; set; }
        public Nullable<int> Paquete { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string REPLEGAL { get; set; }
        public string TelRep { get; set; }
        public string EMailRep { get; set; }
    }
}
