//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteContrato
    {
        public int Id { get; set; }
        public string no_contrato { get; set; }
        public string modalidad_contrato { get; set; }
        public string programa { get; set; }
        public Nullable<int> ejercicio { get; set; }
        public string Proyecto { get; set; }
        public string Procedimiento { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public string DescripcionTrabajo { get; set; }
        public string Localidad { get; set; }
        public string municipio { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<decimal> ImporteContrato { get; set; }
        public Nullable<decimal> ImporteAutorizado { get; set; }
        public Nullable<decimal> anticipo { get; set; }
        public Nullable<decimal> PorcentajeAnticipo { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public string OficioAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaOficio { get; set; }
        public string Empresa { get; set; }
        public string domicilioempresa { get; set; }
        public string CPEmpresa { get; set; }
        public string Correo { get; set; }
        public string RFCEmpresa { get; set; }
        public string Imss { get; set; }
        public string Infonavit { get; set; }
        public string Padron { get; set; }
        public Nullable<decimal> iva { get; set; }
        public string modalidad { get; set; }
        public string TipoInversion { get; set; }
        public string TipoPersona { get; set; }
        public string ClaveRegistro { get; set; }
        public string Director { get; set; }
        public string CargoDireccion { get; set; }
        public string Dependencia { get; set; }
        public string DireccionDependencia { get; set; }
        public string RFCDependencia { get; set; }
        public string siglasDependencia { get; set; }
        public Nullable<int> Paquete { get; set; }
        public int idPaquete { get; set; }
        public string INE { get; set; }
        public string EscrituraPublica { get; set; }
        public string VolumenEscritura { get; set; }
        public Nullable<System.DateTime> FechaEscritura { get; set; }
        public string NumNotario { get; set; }
        public string Notario { get; set; }
        public string Ac_CiudadRPPC { get; set; }
        public Nullable<System.DateTime> Ac_FechaRPPC { get; set; }
        public string FolioMercantilElectronico { get; set; }
        public string LugNot { get; set; }
        public string Ac_NumRPPC { get; set; }
        public string REPLEGAL { get; set; }
        public string CargoRep { get; set; }
        public string RepEscritura { get; set; }
        public string RepVolumen { get; set; }
        public string RepNumNotario { get; set; }
        public string RepNombreNot { get; set; }
        public Nullable<System.DateTime> RepFechaEscritura { get; set; }
        public string RepCiudad { get; set; }
        public string RepCiudadRPPC { get; set; }
        public string CiudadNotariaRep { get; set; }
        public Nullable<System.DateTime> RepRppcFecha { get; set; }
        public string repRpccLibro { get; set; }
        public string RepRFC { get; set; }
        public string RepRppcFolio { get; set; }
        public string AplicaCMIC { get; set; }
        public string inscripcionRPPCRep { get; set; }
        public string FoliosRep { get; set; }
        public string LibropRPPCRep { get; set; }
        public Nullable<System.DateTime> fechafallo { get; set; }
        public Nullable<decimal> AutorizadoProyecto { get; set; }
    }
}
