//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevoSicop.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReporteCaratulaAdq
    {
        public Nullable<int> id { get; set; }
        public int proyectoid { get; set; }
        public Nullable<int> ejercicio { get; set; }
        public string clavepartida { get; set; }
        public string ClaveFF { get; set; }
        public string Procedencia { get; set; }
        public string proyecto { get; set; }
        public string claveProgramatica { get; set; }
        public string no_contrato { get; set; }
        public Nullable<decimal> monto_contrato { get; set; }
        public string Partidadesc { get; set; }
        public string TipoInversion { get; set; }
        public string Programa { get; set; }
        public string modalidad { get; set; }
        public string NoProcedimiento { get; set; }
        public string paqueteDesc { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public string DescripcionTrabajo { get; set; }
        public string DescripcionTrabajo2 { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<decimal> MontoAutorizado { get; set; }
        public Nullable<decimal> anticipo { get; set; }
        public string Oficio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CCT { get; set; }
        public string Contratista { get; set; }
        public string Representante { get; set; }
        public string Empresa { get; set; }
        public string domicilioempresa { get; set; }
        public string CPEmpresa { get; set; }
        public string Correo { get; set; }
        public string RFCEmpresa { get; set; }
        public string Imss { get; set; }
        public string Infonavit { get; set; }
        public string Padron { get; set; }
        public string dep { get; set; }
        public string empLocalidad { get; set; }
        public string CadenaFianzas { get; set; }
    }
}
